# Generated by Django 4.2.6 on 2023-11-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=50)),
                ('em', models.EmailField(max_length=254)),
                ('pn', models.IntegerField()),
                ('np', models.CharField(max_length=8)),
                ('cp', models.CharField(max_length=8)),
            ],
        ),
    ]
